<?php

namespace AppBundle\Repository;

/**
 * AllowedSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowedSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
