<?php

namespace AppBundle\Repository;

/**
 * CartRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRowRepository extends \Doctrine\ORM\EntityRepository
{
}
