<?php

namespace AppBundle\Repository;

/**
 * CartCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
