<?php

namespace AppBundle\Repository;

/**
 * CartCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
