<?php

namespace AppBundle\Repository;

/**
 * DefectiveProductReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefectiveProductReportRepository extends \Doctrine\ORM\EntityRepository
{
}
