<?php

namespace AppBundle\Repository;

/**
 * DefectiveProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefectiveProductRepository extends \Doctrine\ORM\EntityRepository
{
}
