<?php

namespace AppBundle\Repository;

/**
 * MyFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyFileRepository extends \Doctrine\ORM\EntityRepository
{
}
