<?php

namespace AppBundle\Repository;

/**
 * PaymentTermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentTermsRepository extends \Doctrine\ORM\EntityRepository
{
}
