<?php

namespace AppBundle\Repository;

/**
 * SalesmanBrandLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesmanBrandLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
