<?php

namespace AppBundle\Repository;

/**
 * SalesmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesmanRepository extends \Doctrine\ORM\EntityRepository
{
}
