<?php

namespace AppBundle\Repository;

/**
 * SalesmanShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesmanShopRepository extends \Doctrine\ORM\EntityRepository
{
}
