<?php

namespace AppBundle\Repository;

/**
 * SizeQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeQuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
