<?php

namespace AppBundle\Repository;

/**
 * SubSalesmanLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubSalesmanLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
