marques:
    path:    /marketplace-b2b-marques
    defaults:
        _controller: AppBundle:Brand:listBrand

salons_boutiques:
    path:    /salons-mode
    defaults:
        _controller: AppBundle:Salon:listSalon