marques:
    path:    /marketplace-marques-mode
    defaults:
        _controller: AppBundle:Brand:listBrand

salons_boutiques:
    path:    /salons-marques-mode
    defaults:
        _controller: AppBundle:Salon:listSalon


