offres_marques:
   path:    /services-marque-mode
   defaults:
       _controller: AppBundle:Default:offresMarques

showroom:
    path:    /showroom-b2b-mode
    defaults:
        _controller: AppBundle:Default:showroom

agence_commerciale:
    path:    /agent-commercial-mode
    defaults:
        _controller: AppBundle:Default:agenceCommerciale

salons_marques:
    path:    /organisation-salons-mode
    defaults:
        _controller: AppBundle:Default:salonsMarques

tarifs_marques:
    path:    /b2b-marque-tarifs
    defaults:
        _controller: AppBundle:Default:tarifsMarques

details_marques:
    path:    /marque/{marque}
    defaults:
        _controller: AppBundle:BrandDetails:getOneBrand

crm:
    path:    /gestion-clients-marque
    defaults:
            _controller: AppBundle:Default:crm