index:
    path:      /showroom-b2b-mode
    defaults:
        _controller: AppBundle:Default:index

connexion:
    path:    /app/se-connecter
    defaults:
        _controller: AppBundle:Default:connexion


details_marques:
    path:    /{marque}
    defaults:
        _controller: AppBundle:BrandDetails:getOneBrand

details_salons:
    path:    /salon/{ville}-{id}
    defaults:
        _controller: AppBundle:Details:getOneShowroom

marques_index:
    resource: "@AppBundle/Resources/config/routing/marques.yml"
    prefix:   /marques

boutiques_index:
    resource: "@AppBundle/Resources/config/routing/boutiques.yml"
    prefix:   /boutiques

legal_index:
    resource: "@AppBundle/Resources/config/routing/legal.yml"
    prefix:   /legal

info_index:
    resource: "@AppBundle/Resources/config/routing/info.yml"