index:
    path:      /showroom-b2b-mode
    defaults:
        _controller: AppBundle:Default:index

connexion:
    path:    /app/se-connecter
    defaults:
        _controller: AppBundle:Default:connexion

<<<<<<< HEAD

details_marques:
    path:    /{marque}
    defaults:
        _controller: AppBundle:BrandDetails:getOneBrand

=======
>>>>>>> 01dc8f6cadb726136f79c5740da886b4c6afb109
details_salons:
    path:    /salon/{ville}-{id}
    defaults:
        _controller: AppBundle:Details:getOneShowroom

marques_index:
    resource: "@AppBundle/Resources/config/routing/marques.yml"

boutiques_index:
    resource: "@AppBundle/Resources/config/routing/boutiques.yml"

legal_index:
    resource: "@AppBundle/Resources/config/routing/legal.yml"

info_index:
    resource: "@AppBundle/Resources/config/routing/info.yml"